$ErrorActionPreference = "Stop"

Set-Alias vs "$env:ProgramFiles\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe"
Set-Alias code "$env:LOCALAPPDATA\Programs\Microsoft VS Code\bin\code.cmd"
Set-Alias vim "$env:ProgramFiles\Vim\vim90\vim.exe"
Set-Alias gvim "$env:ProgramFiles\Vim\vim90\gvim.exe"
Set-Alias 7z "$env:ProgramFiles\7-zip\7z.exe"
Set-Alias ssh "$env:SystemRoot\System32\OpenSSH\ssh.exe"
Set-Alias scp "$env:SystemRoot\System32\OpenSSH\scp.exe"
Set-Alias less "$env:ProgramFiles\Git\usr\bin\less.exe"
