name: CI

on:
  workflow_dispatch:

  release:
    types:
      - published

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish
        shell: pwsh
        run: |
          Import-Module ./Dev.psm1
          Publish-DevModule
