name: CI

on:
  workflow_dispatch:

  release:
    types:
      - published

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      REGISTRY_RW_PAT: ${{secrets.REGISTRY_RW_PAT}}
    steps:
      - name: Setup PowerShell
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Microsoft.PowerShell.PSResourceGet
          Register-PSResourceRepository GitHub `
            -Uri "https://nuget.pkg.github.com/$env:GITHUB_REPOSITORY_OWNER/index.json"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish FkThat.PowerShell
        shell: pwsh
        run: >-
          Publish-PSResource src/FkThat.PowerShell
          -Repository GitHub -ApiKey $env:REGISTRY_RW_PAT
